"""Persistence protocol for memory backends."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from active_memory.models import Memory, MemoryEdge, MemoryFilters, Message


class MemoryStore(Protocol):
    def add_message(self, message: Message) -> None: ...
    def add_memory(self, memory: Memory) -> None: ...
    def add_edges(self, edges: Sequence[MemoryEdge]) -> None: ...
    def get_recent_messages(self, session_id: str, limit: int) -> list[Message]: ...
    def get_active_memories(self, namespace: str, filters: MemoryFilters | None = None) -> list[Memory]: ...
    def get_memories_by_ids(self, memory_ids: Sequence[str]) -> list[Memory]: ...
    def get_neighbors(self, memory_ids: Sequence[str], edge_types: set[str] | None = None) -> list[MemoryEdge]: ...
    def mark_included(self, memory_ids: Sequence[str], included_at: datetime) -> None: ...
    def supersede_memory(self, old_memory_id: str, new_memory_id: str, superseded_at: datetime) -> None: ...
    def complete_context_assembly(self, session_id: str, namespace: str, memory_ids: Sequence[str], input_tokens: int, created_at: datetime, metadata: dict | None = None) -> None: ...
